Repository iOS-vk-education/2023_2_CakesHub, pull requests merged in 2024-05, with the labels that each got.

#43 iOS-31 | Добавлена архитектура для экрана настроек. Внедрена логика выхода их аккаунта
  CakesHub/CakesHub.xcodeproj/project.pbxproj
  CakesHub/CakesHub/Application/MainView/ViewModel/RootViewModel.swift
  CakesHub/CakesHub/Application/Navigation.swift
  CakesHub/CakesHub/Streams/ProfileStream/AuthScreen/Model/VMAuthReducers.swift
  CakesHub/CakesHub/Streams/ProfileStream/AuthScreen/Model/VMAuthScreenData.swift
  CakesHub/CakesHub/Streams/ProfileStream/AuthScreen/View/AuthSubviews.swift
  CakesHub/CakesHub/Streams/ProfileStream/AuthScreen/View/AuthView.swift
  CakesHub/CakesHub/Streams/ProfileStream/AuthScreen/ViewModel/AuthViewModel+Mock.swift
  CakesHub/CakesHub/Streams/ProfileStream/AuthScreen/ViewModel/AuthViewModel.swift
  CakesHub/CakesHub/Streams/ProfileStream/ProfileScreen/View/Screens/SettingsView.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/Model/SettingsVMData.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/Model/SettingsVMReducers.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/Model/SettingsVMServices.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/Model/SettingsVMUIProperties.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/View/SettingsView.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/View/Subviews/SettingsSubview.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/ViewModel/SettingsViewModel+Mock.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/ViewModel/SettingsViewModel.swift
Labels: feature

#44 iOS-32 | Добавлен экран авторизации
  CakesHub/CakesHub.xcodeproj/project.pbxproj
  CakesHub/CakesHub.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CakesHub/CakesHub.xcodeproj/xcshareddata/xcschemes/CakesHub.xcscheme
  CakesHub/CakesHub/Streams/ProfileStream/AuthScreen/View/AuthorizationView.swift
Labels: feature

#45 iOS-33 | Внедрение MVVM и сетевой логики к экрану авторизации
  CakesHub/CakesHub.xcodeproj/project.pbxproj
  CakesHub/CakesHub.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CakesHub/CakesHub.xcodeproj/xcshareddata/xcschemes/CakesHub.xcscheme
  CakesHub/CakesHub/Services/WebSocket/WebSockerManager.swift
  CakesHub/CakesHub/Streams/ProfileStream/AuthScreen/View/AuthSubviews.swift
  CakesHub/CakesHub/Streams/ProfileStream/AuthScreen/View/AuthorizationView.swift
  CakesHubAPI/Sources/App/entrypoint.swift
Labels: feature

#42 iOS-30 | Добавлена карта
  CakesHub/CakesHub.xcodeproj/project.pbxproj
  CakesHub/CakesHub/Application/CakesHubApp.swift
  CakesHub/CakesHub/Application/MainView/ViewModel/RootViewModel.swift
  CakesHub/CakesHub/Application/Navigation.swift
  CakesHub/CakesHub/Streams/ProductStream/ProductDetail/RatingReviewsScreen/Model/ProductReviewsModel.swift
  CakesHub/CakesHub/Streams/ProfileStream/AuthScreen/Model/VMAuthReducers.swift
  CakesHub/CakesHub/Streams/ProfileStream/AuthScreen/Model/VMAuthScreenData.swift
  CakesHub/CakesHub/Streams/ProfileStream/AuthScreen/View/AuthSubviews.swift
  CakesHub/CakesHub/Streams/ProfileStream/AuthScreen/View/AuthView.swift
  CakesHub/CakesHub/Streams/ProfileStream/AuthScreen/ViewModel/AuthViewModel+Mock.swift
  CakesHub/CakesHub/Streams/ProfileStream/AuthScreen/ViewModel/AuthViewModel.swift
  CakesHub/CakesHub/Streams/ProfileStream/ProfileScreen/Model/ProfileVMScreens.swift
  CakesHub/CakesHub/Streams/ProfileStream/ProfileScreen/View/Screens/ProfileScreen.swift
  CakesHub/CakesHub/Streams/ProfileStream/ProfileScreen/View/Screens/SettingsView.swift
  CakesHub/CakesHub/Streams/ProfileStream/ProfileScreen/View/Subviews/ProfileSubviews.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/Model/SettingsVMData.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/Model/SettingsVMReducers.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/Model/SettingsVMServices.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/Model/SettingsVMUIProperties.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/View/SettingsView.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/View/Subviews/SettingsSubview.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/ViewModel/SettingsViewModel+Mock.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/ViewModel/SettingsViewModel.swift
  CakesHub/CakesHub/Streams/ProfileStream/UserLocationScreen/Model/UserLocationVMData.swift
  CakesHub/CakesHub/Streams/ProfileStream/UserLocationScreen/Model/UserLocationVMReducers.swift
  CakesHub/CakesHub/Streams/ProfileStream/UserLocationScreen/Model/UserLocationVMUIProperties.swift
  CakesHub/CakesHub/Streams/ProfileStream/UserLocationScreen/View/Subviews/LocationDetailsView.swift
  CakesHub/CakesHub/Streams/ProfileStream/UserLocationScreen/View/Subviews/UserLocationSubview.swift
  CakesHub/CakesHub/Streams/ProfileStream/UserLocationScreen/View/UserLocationView.swift
  CakesHub/CakesHub/Streams/ProfileStream/UserLocationScreen/ViewModel/LocationManager.swift
  CakesHub/CakesHub/Streams/ProfileStream/UserLocationScreen/ViewModel/UserLocationViewModel.swift
  Xcode Templates/VK-CakesHub/SwiftUI-MVVM.xctemplate/TemplateInfo.plist
  Xcode Templates/VK-CakesHub/SwiftUI-MVVM.xctemplate/___FILEBASENAME___Screen/Model/___FILEBASENAME___VMData.swift
  Xcode Templates/VK-CakesHub/SwiftUI-MVVM.xctemplate/___FILEBASENAME___Screen/Model/___FILEBASENAME___VMReducers.swift
  Xcode Templates/VK-CakesHub/SwiftUI-MVVM.xctemplate/___FILEBASENAME___Screen/Model/___FILEBASENAME___VMUIProperties.swift
  Xcode Templates/VK-CakesHub/SwiftUI-MVVM.xctemplate/___FILEBASENAME___Screen/View/Subviews/___FILEBASENAME___Subview.swift
  Xcode Templates/VK-CakesHub/SwiftUI-MVVM.xctemplate/___FILEBASENAME___Screen/View/___FILEBASENAME___View.swift
  Xcode Templates/VK-CakesHub/SwiftUI-MVVM.xctemplate/___FILEBASENAME___Screen/ViewModel/___FILEBASENAME___ViewModel+Mock.swift
  Xcode Templates/VK-CakesHub/SwiftUI-MVVM.xctemplate/___FILEBASENAME___Screen/ViewModel/___FILEBASENAME___ViewModel.swift
Labels: feature

#41 iOS-29 | Добавлены локальные пуши
  CakesHub/CakesHub.xcodeproj/project.pbxproj
  CakesHub/CakesHub/Application/AppDelegate.swift
  CakesHub/CakesHub/Application/CakesHubApp.swift
  CakesHub/CakesHub/Application/MainView/ViewModel/RootViewModel.swift
  CakesHub/CakesHub/Application/Navigation.swift
  CakesHub/CakesHub/Services/Notifications/LocalNotificationManager.swift
  CakesHub/CakesHub/Streams/ProductStream/ProductDetail/RatingReviewsScreen/Model/ProductReviewsModel.swift
  CakesHub/CakesHub/Streams/ProfileStream/AuthScreen/Model/VMAuthReducers.swift
  CakesHub/CakesHub/Streams/ProfileStream/AuthScreen/Model/VMAuthScreenData.swift
  CakesHub/CakesHub/Streams/ProfileStream/AuthScreen/View/AuthSubviews.swift
  CakesHub/CakesHub/Streams/ProfileStream/AuthScreen/View/AuthView.swift
  CakesHub/CakesHub/Streams/ProfileStream/AuthScreen/ViewModel/AuthViewModel+Mock.swift
  CakesHub/CakesHub/Streams/ProfileStream/AuthScreen/ViewModel/AuthViewModel.swift
  CakesHub/CakesHub/Streams/ProfileStream/ProfileScreen/Model/ProfileVMScreens.swift
  CakesHub/CakesHub/Streams/ProfileStream/ProfileScreen/View/Screens/ProfileScreen.swift
  CakesHub/CakesHub/Streams/ProfileStream/ProfileScreen/View/Screens/SettingsView.swift
  CakesHub/CakesHub/Streams/ProfileStream/ProfileScreen/View/Subviews/ProfileSubviews.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/Model/SettingsVMData.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/Model/SettingsVMReducers.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/Model/SettingsVMServices.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/Model/SettingsVMUIProperties.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/View/SettingsView.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/View/Subviews/SettingsSubview.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/ViewModel/SettingsViewModel+Mock.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/ViewModel/SettingsViewModel.swift
  CakesHub/CakesHub/Streams/ProfileStream/UserLocationScreen/Model/UserLocationVMData.swift
  CakesHub/CakesHub/Streams/ProfileStream/UserLocationScreen/Model/UserLocationVMReducers.swift
  CakesHub/CakesHub/Streams/ProfileStream/UserLocationScreen/Model/UserLocationVMUIProperties.swift
  CakesHub/CakesHub/Streams/ProfileStream/UserLocationScreen/View/Subviews/LocationDetailsView.swift
  CakesHub/CakesHub/Streams/ProfileStream/UserLocationScreen/View/Subviews/UserLocationSubview.swift
  CakesHub/CakesHub/Streams/ProfileStream/UserLocationScreen/View/UserLocationView.swift
  CakesHub/CakesHub/Streams/ProfileStream/UserLocationScreen/ViewModel/LocationManager.swift
  CakesHub/CakesHub/Streams/ProfileStream/UserLocationScreen/ViewModel/UserLocationViewModel.swift
  Xcode Templates/VK-CakesHub/SwiftUI-MVVM.xctemplate/TemplateInfo.plist
  Xcode Templates/VK-CakesHub/SwiftUI-MVVM.xctemplate/___FILEBASENAME___Screen/Model/___FILEBASENAME___VMData.swift
  Xcode Templates/VK-CakesHub/SwiftUI-MVVM.xctemplate/___FILEBASENAME___Screen/Model/___FILEBASENAME___VMReducers.swift
  Xcode Templates/VK-CakesHub/SwiftUI-MVVM.xctemplate/___FILEBASENAME___Screen/Model/___FILEBASENAME___VMUIProperties.swift
  Xcode Templates/VK-CakesHub/SwiftUI-MVVM.xctemplate/___FILEBASENAME___Screen/View/Subviews/___FILEBASENAME___Subview.swift
  Xcode Templates/VK-CakesHub/SwiftUI-MVVM.xctemplate/___FILEBASENAME___Screen/View/___FILEBASENAME___View.swift
  Xcode Templates/VK-CakesHub/SwiftUI-MVVM.xctemplate/___FILEBASENAME___Screen/ViewModel/___FILEBASENAME___ViewModel+Mock.swift
  Xcode Templates/VK-CakesHub/SwiftUI-MVVM.xctemplate/___FILEBASENAME___Screen/ViewModel/___FILEBASENAME___ViewModel.swift
Labels: feature

#46 iOS-34 | Убрана анимация появления отзывов. Добавлена сортировка ячеек сообщений
  CakesHub/CakesHub/Streams/ProductStream/ProductDetail/RatingReviewsScreen/View/Subviews/ProductReviewsSubviews.swift
  CakesHub/CakesHub/Streams/ProfileStream/ProfileScreen/View/Screens/ProfileScreen.swift
  CakesHub/CakesHub/Streams/WebSocketStream/AllChatsScreen/Model/ChatCellModel.swift
  CakesHub/CakesHub/Streams/WebSocketStream/AllChatsScreen/View/Subviews/AllChatsSubview.swift
  CakesHub/CakesHub/Streams/WebSocketStream/AllChatsScreen/ViewModel/AllChatsViewModel+Mock.swift
  CakesHub/CakesHub/Streams/WebSocketStream/AllChatsScreen/ViewModel/AllChatsViewModel.swift
Labels: feature, fix bug

#48 iOS-36 | Правки по UI
  CakesHub/CakesHub/Services/Firebase/Services/Product/CakeService.swift
  CakesHub/CakesHub/Streams/DesignSystemStream/Components/CHMBigBannerView/CHMBigBannerView.swift
  CakesHub/CakesHub/Streams/DesignSystemStream/Components/CHMBigBannerView/Configuration/CHMBigBannerView+Configuration.swift
  CakesHub/CakesHub/Streams/DesignSystemStream/Components/CHMBigBannerView/Configuration/CHMBigBannerView+Defaults.swift
  CakesHub/CakesHub/Streams/DesignSystemStream/Components/CHMRatingReviewsView/CHMRatingReviewsView.swift
  CakesHub/CakesHub/Streams/DesignSystemStream/Components/CustomTabBar.swift
  CakesHub/CakesHub/Streams/ProductStream/CreateProductScreen/View/CreateProductSubviews.swift
  CakesHub/CakesHub/Streams/ProductStream/CreateProductScreen/View/CreateProductView.swift
  CakesHub/CakesHub/Streams/ProductStream/CreateProductScreen/View/Steps/AddProductImages.swift
  CakesHub/CakesHub/Streams/ProductStream/CreateProductScreen/View/Steps/ProductResultScreen.swift
  CakesHub/CakesHub/Streams/ProductStream/MainScreen/ViewModel/MainViewModel+Mock.swift
  CakesHub/CakesHub/Streams/ProductStream/ProductDetail/RatingReviewsScreen/Model/ProductReviewsModel.swift
  CakesHub/CakesHub/Streams/ProductStream/ProductDetail/RatingReviewsScreen/View/Subviews/ProductReviewsSubviews.swift
  CakesHub/CakesHub/Streams/WebSocketStream/NotificationScreen/View/NotificationView.swift
  CakesHub/CakesHub/Streams/WebSocketStream/NotificationScreen/View/Subviews/NotificationCell.swift
Labels: feature

#55 iOS-42 | Внедрение экрана настроек в проект
  CakesHub/CakesHub.xcodeproj/project.pbxproj
  CakesHub/CakesHub.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CakesHub/CakesHub.xcodeproj/xcshareddata/xcschemes/CakesHub-Ru.xcscheme
  CakesHub/CakesHub.xcodeproj/xcshareddata/xcschemes/CakesHub.xcscheme
  CakesHub/CakesHub/Application/MainView/Model/VMRootServices.swift
  CakesHub/CakesHub/Application/MainView/View/RootView.swift
  CakesHub/CakesHub/Application/MainView/ViewModel/RootViewModel.swift
  CakesHub/CakesHub/Resources/Launch Screen.storyboard
  CakesHub/CakesHub/Resources/Localizable.xcstrings
  CakesHub/CakesHub/Services/Firebase/Services/User/AuthService.swift
  CakesHub/CakesHub/Services/Firebase/Services/User/UserService.swift
  CakesHub/CakesHub/Streams/ProductStream/CreateProductScreen/ViewModel/CreateProductViewModel.swift
  CakesHub/CakesHub/Streams/ProfileStream/AuthScreen/ViewModel/AuthViewModel.swift
  CakesHub/CakesHub/Streams/ProfileStream/ProfileScreen/View/ProfileScreen.swift
  CakesHub/CakesHub/Streams/ProfileStream/ProfileScreen/View/Screens/EditNameView.swift
  CakesHub/CakesHub/Streams/ProfileStream/ProfileScreen/View/Screens/EditPasswordView.swift
  CakesHub/CakesHub/Streams/ProfileStream/ProfileScreen/View/Screens/EditProfileView.swift
  CakesHub/CakesHub/Streams/ProfileStream/ProfileScreen/View/Screens/EditStatusView.swift
  CakesHub/CakesHub/Streams/ProfileStream/ProfileScreen/ViewModel/ProfileViewModel.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/Model/SettingsVMServices.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/Model/SettingsVMUIProperties.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/View/DeprecatedSubviews/EditEmailView.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/View/DeprecatedSubviews/EditNameView.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/View/DeprecatedSubviews/EditPasswordView.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/View/DeprecatedSubviews/EditProfileView.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/View/DeprecatedSubviews/NotificationsView.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/View/DeprecatedSubviews/SettingButtonsModifier.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/View/DeprecatedSubviews/SupportView.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/View/SettingsView.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/View/Subviews/SettingsSubview.swift
  CakesHub/CakesHub/Streams/ProfileStream/SettingsScreen/ViewModel/SettingsViewModel.swift
  CakesHub/CakesHub/Streams/WebSocketStream/AllChatsScreen/View/Subviews/AllChatsSubview.swift
Labels: На проверке, feature

#52 iOS-32 | Добавлен экран регистрации
  CakesHub/CakesHub.xcodeproj/project.pbxproj
  CakesHub/CakesHub/Helpers/Extensions/FlipTransaction.swift
  CakesHub/CakesHub/Helpers/Extensions/SwiftUI/AnyTransition+Extenstions.swift
  CakesHub/CakesHub/Services/WebSocket/WebSockerManager.swift
  CakesHub/CakesHub/Streams/ProfileStream/AuthScreen/Model/VMAuthUIProperties.swift
  CakesHub/CakesHub/Streams/ProfileStream/AuthScreen/View/AuthSubviews.swift
  CakesHub/CakesHub/Streams/ProfileStream/AuthScreen/View/AuthView.swift
  CakesHub/CakesHub/Streams/ProfileStream/AuthScreen/View/AuthorizationView.swift
  CakesHub/CakesHub/Streams/ProfileStream/AuthScreen/View/RegisterView.swift
  CakesHub/CakesHub/Streams/ProfileStream/AuthScreen/ViewModel/AuthViewModel+Mock.swift
  CakesHub/CakesHub/Streams/ProfileStream/AuthScreen/ViewModel/AuthViewModel.swift
  CakesHubAPI/Sources/App/entrypoint.swift
Labels: feature

#57 iOS-42 | Добавлена кнопка удаления товара
  CakesHub/CakesHub/Application/MainView/ViewModel/RootViewModel.swift
  CakesHub/CakesHub/Resources/Launch Screen.storyboard
  CakesHub/CakesHub/Resources/Localizable.xcstrings
  CakesHub/CakesHub/Services/Firebase/Services/Product/CakeService.swift
  CakesHub/CakesHub/Streams/ProductStream/ProductDetail/ProductDetailScreen/Model/ProductDetailVMServices.swift
  CakesHub/CakesHub/Streams/ProductStream/ProductDetail/ProductDetailScreen/View/ProductDetailScreen.swift
  CakesHub/CakesHub/Streams/ProductStream/ProductDetail/ProductDetailScreen/View/Subviews/ProductDetailSubviews.swift
  CakesHub/CakesHub/Streams/ProductStream/ProductDetail/ProductDetailScreen/ViewModel/ProductDetailViewModel.swift
Labels: На проверке, feature

#58 iOS-43 | Добавлена группировка похожих товаров
  CakesHub/CakesHub/Application/MainView/ViewModel/RootViewModel.swift
  CakesHub/CakesHub/Memory/SwiftDataModels/SDProductModel.swift
  CakesHub/CakesHub/Services/Firebase/Entities/FBProductModel/FBProductModel.swift
  CakesHub/CakesHub/Streams/ProductStream/CategoriesScreen/View/CategoriesView.swift
Labels: На проверке, feature
